### ISSUE TITLE
使用Mint-ui实现滚动加载

### ISSUE THREAD

**Issue by CruxF** [CruxF/Vue-base#20]
# 开发环境
- vue
- vue-cli
- less
- mint-ui
<br><br>

# 开发步骤一
- 通过脚手架创建vue项目，安装mint-ui：npm install mint-ui -S
- 在项目中引入mint-ui
```js
import Vue from 'vue'
import App from './App'
import router from './router'
import 'mint-ui/lib/style.css'
import { InfiniteScroll, Spinner } from 'mint-ui';
Vue.component(Spinner.name, Spinner);
Vue.use(InfiniteScroll);
Vue.config.productionTip = false

new Vue({
  el: '#app',
  router,
  components: { App },
  template: '<App/>'
})
```
- 安装less：npm install less less-loader --save-dev
- 移动端适配（代码位置：index.html)
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">
    <title>Demo</title>
  </head>
  <body>
    <noscript>
      <strong>We're sorry but s3_recharge doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
  </body>
  <script> 
    //屏幕适配
    (function (win, doc) {
      if (!win.addEventListener) return;
      var html = document.documentElement;
      function setFont() {
        var html = document.documentElement;
        var k = 740;
        html.style.fontSize = html.clientWidth / k * 100 + "px";
      }
      setFont();
      setTimeout(function () {
        setFont();
      }, 300);
      doc.addEventListener('DOMContentLoaded', setFont, false);
      win.addEventListener('resize', setFont, false);
      win.addEventListener('load', setFont, false);
      document.documentElement.addEventListener('touchstart', function (event) {
        if (event.touches.length > 1) {
          event.preventDefault();
        }
      }, false);
      var lastTouchEnd = 0;
      document.documentElement.addEventListener('touchend', function (event) {
        var now = Date.now();
        if (now - lastTouchEnd <= 300) {
          event.preventDefault();
        }
        lastTouchEnd = now;
      }, false);
      // 解决ios safari无法禁止双指缩放问题
      document.addEventListener('gesturestart', function (event) {
        event.preventDefault();
      });
    })(window, document);
</script>
</html>
```
- 创建重置样式，并在APP.vue文件中引入
```css
html,
body,
#app {
  width: 100%;
  height: 100%;
  padding: 0;
  margin: 0;
  font-family: 'Microsoft YaHei UI';
  box-sizing: border-box;
  position: relative;
  z-index: -1;
}
h1,
h2,
h3,
h4,
h5,
p,
ul,
li,
button,
a {
  padding: 0;
  margin: 0;
  font-weight: normal;
}
a {
  text-decoration: none;
}
ul,
li {
  list-style: none;
}
button {
  border: none;
  outline: none
}
/* 金黄色 */
.golden {
  color: #ec9c00;
}
/* 灰色背景色 */
.graybgc {
  background-color: #eee;
}
/* 深灰色字体色 */
.graytext {
  color: #717171;
}
span {
  display: inline-block;
  vertical-align: middle;
}
```

# 开发步骤二
编写结构代码
```html
<template>
  <div class="order-list graybgc">
    <div class="order-wrapper">
      <div
        class="order-info"
        ref="itemwrapper"
        v-show="dealList && dealList.length > 0"
        v-infinite-scroll="loadMore"
        infinite-scroll-disabled="loading"
        infinite-scroll-distance="50"
      >
        <div>
          <div class="order-box" v-for="(item, index) in dealList" :key="index">
            <div class="header">
              <div class="user-info">
                <span class="game-name">火影忍者</span>
                <span class="game-serve">
                  张三丰-微信17区
                </span>
              </div>
              <div class="order-status">
                <span class="success golden">支付成功</span>
              </div>
            </div>
            <div class="info">
              <div class="info-img">
                <img
                  src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1583325310315&di=8d5d1b8c9a22543bfc5c8fad58ff79cf&imgtype=0&src=http%3A%2F%2Fimages.china.cn%2Fattachement%2Fjpg%2Fsite1000%2F20141203%2F7427ea21095115e896280f.jpg"
                  alt=""
                />
              </div>
              <div class="info-number">
                <div class="title">
                  新春礼包
                </div>
                <div class="money">
                  单价：￥10/ 件
                </div>
                <div class="number">数量：20 件</div>
              </div>
            </div>
            <div class="footer">
              <div class="time graytext">
                <span class="date">02-10 22:00</span>
              </div>
              <div class="total-money">
                <span class="text graytext">合计：</span>
                <div class="money">
                  <span class="min">￥</span>
                  <span>200</span>
                </div>
              </div>
            </div>
          </div>
          
          <p v-show="loading" class="bottom-tip">
            <mt-spinner color="#26a2ff"></mt-spinner>
          </p>
          <div class="null-box"></div>
        </div>
      </div>
      <div class="order-no" v-if="!dealList || dealList.length == 0">
        <div class="img"></div>
        <div class="desc graytext">暂时还没您的购买记录哦</div>
      </div>
    </div>
    <div class="order-footer graytext">
      当前页面仅提供30天记录查询，如有疑问，请
      <a href="#">联系客服</a>
    </div>
  </div>
</template>
```
<br><br>

# 开发步骤三
编写样式代码
```css
<style scoped lang="less">
.order-list {
  position: relative;
  width: 100%;
  min-height: 100%;
  padding: 0.25rem 0.4rem 0;
  box-sizing: border-box;
  .order-wrapper {
    .order-info {
      width: 100%;
      height: 90vh;
      overflow-y: scroll;
      -webkit-overflow-scrolling: touch;
      .top-tip {
        width: 100%;
        height: 0.6rem;
        line-height: 0.1rem;
        text-align: center;
      }
      .order-box {
        background-color: #fff;
        padding: 0.15rem 0.3rem;
        box-sizing: border-box;
        border-radius: 0.05rem;
        font-size: 0.2rem;
        margin-bottom: 0.3rem;
        .header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          .user-info {
            color: #000;
            text-align: left;
            .game-name {
              margin-right: 0.1rem;
            }
          }
          .order-status {
            .no-play-btn {
              padding: 0.01rem 0.2rem;
              background-color: #ec6f00;
              color: #fff;
              border-radius: 0.2rem;
              margin-left: 0.1rem;
            }
          }
        }
        .info {
          display: flex;
          width: 100%;
          padding: 0.1rem 0 0.15rem;
          box-sizing: border-box;
          border-bottom: 0.02rem solid #d5d5d5;
          .info-img {
            display: inline-block;
            vertical-align: top;
            width: 1.1rem;
            height: 1.1rem;
            background-color: #ec6f00;
            text-align: center;
            line-height: 1.1rem;
            margin-right: 0.2rem;
            position: relative;
            img {
              position: absolute;
              left: 50%;
              top: 50%;
              transform: translate(-50%, -50%);
              display: inline-block;
              width: 0.8rem;
              height: 0.8rem;
              border-radius: 50%;
            }
          }
          .info-number {
            display: inline-block;
            vertical-align: top;
            height: 1.1rem;
            text-align: left;
            padding: 0;
            margin: 0;
            .title {
              font-size: 0.28rem;
              color: #000;
            }
          }
        }
        .footer {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding-top: 0.15rem;
          .money {
            display: inline-block;
            vertical-align: middle;
            font-size: 0.28rem;
            color: #000;
            span {
              vertical-align: baseline;
            }
            .min {
              font-size: 0.22rem;
            }
          }
        }
      }
      .null-box {
        width: 100%;
        height: 1px;
      }
      .bottom-tip {
        text-align: center;
        margin-top: -0.2rem;
        height: 1rem;
        line-height: 1rem;
      }
    }
    .order-no {
      position: absolute;
      left: 50%;
      top: 50%;
      transform: translate(-50%, -50%) !important;
      width: 4rem;
      height: 5rem;
      text-align: center;
      .img {
        width: 1.38rem;
        height: 1.8rem;
        background-color: #eee;
        margin: 0 auto;
      }
      .desc {
        margin-top: 0.4rem;
        font-size: 0.3rem;
      }
    }
  }
  .order-footer {
    width: 100%;
    height: 0.6rem;
    line-height: 0.6rem;
    position: fixed;
    bottom: 0;
    left: 0;
    font-size: 0.24rem;
    background-color: inherit;
    z-index: 1;
    text-align: center;
    a {
      text-decoration: underline;
      color: #000;
    }
  }
}
</style>
```
<br><br>

# 开发步骤四
编写js代码
```js
<script>
export default {
  name: "OrderList",
  data() {
    return {
      pageIndex: 1,
      dealList: [], //订单记录列表
      loading: false,
      allLoaded: false,
      lock: false //避免同一时间多次请求数据
    };
  },
  created() {
    this.getOrderList();
  },
  methods: {
    loadMore() {
      if (this.allLoaded) {
        return;
      }
      this.loading = true;
      setTimeout(() => {
        this.pageIndex++;
        this.getOrderList();
      }, 1500);   
    },
    // 获取订单列表数据
    getOrderList(status) {
      let data = [1, 2, 3]; //模拟接口返回的数据
      this.loading = false;
      if (data && data.length > 0) {
        if (this.pageIndex > 1) {
          this.dealList = this.dealList.concat(data);
        } else {
          this.dealList = data;
        }
      } else {
        //没有数据
        this.allLoaded = true;
      }
    }
  }
};
</script>
```
<br><br>
